#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export TERM=xterm-256color

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# zsh
export ZSH="$XDG_CONFIG_HOME/oh-my-zsh"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_CUSTOM="$XDG_CONFIG_HOME/oh-my-zsh/custom"
export HISTFILE="$ZDOTDIR/.zsh_history"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file
export DISABLE_UPDATE_PROMPT=true
export DISABLE_AUTO_UPDATE=true
export _Z_DATA="$ZDOTDIR/.z" # z data file
export ZSH_THEME="powerlevel10k/powerlevel10k"

# p10k
export POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# fzf
export FZF_DEFAULT_OPTS='--height 60% --layout=reverse --bind ctrl-e:down,ctrl-u:up --preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"'
export FZF_COMPLETION_TRIGGER='**'
export FZF_TMUX=1
export FZF_TMUX_HEIGHT='80%'
export fzf_preview_cmd='[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500'
export FZF_DEFAULT_COMMAND='rg --files-with-matches --no-messages --hidden --glob "!.m2" --glob "!.idea" --glob "!target" --glob "!.vscode" --glob "!.git" --glob "!.cache/bazel" ""'
export PATH="$PATH:$HOME/.fzf/bin"

# go
export CGO_CPPFLAGS="-Wno-error -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-builtin-requires-header"
